modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="dimensional_expansion" #mandatory
version="0.2a" #mandatory
displayName="Dimensional Expansion Mod" #mandatory
logoFile="textures/logo/logo.png" #optional
credits="" #optional
authors="Killar.exe" #optional
description=''''''
updateJSONURL="https://raw.githubusercontent.com/Killarexe/Dimensional-Expansion/main/update.json"
[[dependencies.dimensional_expansion]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.dimensional_expansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
