modLoader="javafml"
loaderVersion="[44,)"
license="CC0 1.0 Universal"
[[mods]]
modId="dimensional_expansion"
version="0.7.1a"
displayName="Dimensional Expansion Mod"
logoFile="logo.png"
credits="This Mod made by Killar.exe and with the help of the community and 9è_Docteur."
authors="Killar.exe" #optional
description='''Dimensional Expansion is a mod made by Killar.exe...'''
updateJSONURL="https://raw.githubusercontent.com/Killarexe/Dimensional-Expansion/main/update.json"
[[dependencies.dimensional_expansion]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44.0.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.dimensional_expansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20)"
    ordering="NONE"
    side="BOTH"
