modLoader="javafml"
loaderVersion="[40,)"
license="Creative Commons Attribution-NonCommercial 3.0"
[[mods]]
modId="dimensional_expansion"
version="0.6a"
displayName="Dimensional Expansion Mod"
logoFile="pack.png"
credits="This Mod made bt Killar.exe"
authors="Killar.exe" #optional
description='''Dimensional Expansion is a mod who adds a lot of new things like: Blocks, Items, Ores, Biomes and more!'''
updateJSONURL="https://raw.githubusercontent.com/Killarexe/Dimensional-Expansion/main/update.json"
[[dependencies.dimensional_expansion]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.dimensional_expansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
